swagger: "2.0"
info:
  title: An api for fruit shop online purchases
  description: This api manages online fruit shop with CRUD operations
  version: ""
host: localhost:8080
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /api/v1/cart/{cartId}:
    get:
      tags:
      - cart
      summary: get cart
      operationId: cart#get
      parameters:
      - name: cartId
        in: path
        description: cartId
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/CartCartManagementResponseCollection'
      schemes:
      - http
    post:
      tags:
      - cart
      summary: add cart
      operationId: cart#add
      parameters:
      - name: cartId
        in: path
        description: cartId of the user
        required: true
        type: string
      - name: AddRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/CartAddRequestBody'
          required:
          - Name
          - Count
      responses:
        "201":
          description: Created response.
      schemes:
      - http
  /api/v1/fruit:
    get:
      tags:
      - fruit
      summary: show fruit
      operationId: fruit#show
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/FruitFruitManagementResponseCollection'
      schemes:
      - http
  /api/v1/fruit/{Name}:
    get:
      tags:
      - fruit
      summary: get fruit
      operationId: fruit#get
      parameters:
      - name: Name
        in: path
        description: Name
        required: true
        type: string
      - name: GetRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/FruitGetRequestBody'
          required:
          - Cost
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/FruitGetResponseBody'
      schemes:
      - http
  /api/v1/user:
    get:
      tags:
      - user
      summary: show user
      operationId: user#show
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/UserUserManagementResponseCollection'
      schemes:
      - http
  /api/v1/user/{ID}:
    get:
      tags:
      - user
      summary: get user
      operationId: user#get
      parameters:
      - name: ID
        in: path
        description: ID
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/UserGetResponseBody'
      schemes:
      - http
    post:
      tags:
      - user
      summary: add user
      operationId: user#add
      parameters:
      - name: ID
        in: path
        description: ID
        required: true
        type: string
      - name: AddRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/UserAddRequestBody'
          required:
          - UserName
      responses:
        "201":
          description: Created response.
      schemes:
      - http
  /openapi.json:
    get:
      tags:
      - user
      summary: Download ./gen/http/openapi.json
      operationId: user#/openapi.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
definitions:
  CartAddRequestBody:
    title: CartAddRequestBody
    type: object
    properties:
      Count:
        type: integer
        description: Number of fruits
        example: 4039646094160476520
        format: int64
      Name:
        type: string
        description: Name of the fruit
        example: Quo et tempore.
    example:
      Count: 3327328163604553417
      Name: Sint vitae officiis.
    required:
    - Name
    - Count
  CartCartManagementResponseCollection:
    title: 'Mediatype identifier: application/vnd.cart; type=collection; view=default'
    type: array
    items:
      $ref: '#/definitions/CartManagementResponse'
    description: GetResponseBody is the result type for an array of CartManagementResponse (default view)
    example:
    - Count: 2
      Name: Apple
      cartId: "1"
    - Count: 2
      Name: Apple
      cartId: "1"
    - Count: 2
      Name: Apple
      cartId: "1"
  CartManagementResponse:
    title: 'Mediatype identifier: application/vnd.cart; view=default'
    type: object
    properties:
      Count:
        type: integer
        description: Number of fruits
        example: 2
        format: int64
      Name:
        type: string
        description: Name of the fruit
        example: Apple
      cartId:
        type: string
        description: cartId is the unique id of the User.
        example: "1"
    description: A CartManagement type describes users cart state. (default view)
    example:
      Count: 2
      Name: Apple
      cartId: "1"
    required:
    - cartId
    - Name
    - Count
  FruitFruitManagementResponseCollection:
    title: 'Mediatype identifier: application/vnd.fruit; type=collection; view=default'
    type: array
    items:
      $ref: '#/definitions/FruitManagementResponse'
    description: ShowResponseBody is the result type for an array of FruitManagementResponse (default view)
    example:
    - Cost: 1
      Name: Apple
    - Cost: 1
      Name: Apple
    - Cost: 1
      Name: Apple
  FruitGetRequestBody:
    title: FruitGetRequestBody
    type: object
    properties:
      Cost:
        type: number
        description: Cost
        example: 0.9509512832245888
        format: double
    example:
      Cost: 0.5448498531255602
    required:
    - Cost
  FruitGetResponseBody:
    title: 'Mediatype identifier: application/vnd.fruit; view=default'
    type: object
    properties:
      Cost:
        type: number
        description: Cost of the Fruit.
        example: 1
        format: double
      Name:
        type: string
        description: Name is the unique Name of the Fruit.
        example: Apple
    description: GetResponseBody result type (default view)
    example:
      Cost: 1
      Name: Apple
    required:
    - Name
    - Cost
  FruitManagementResponse:
    title: 'Mediatype identifier: application/vnd.fruit; view=default'
    type: object
    properties:
      Cost:
        type: number
        description: Cost of the Fruit.
        example: 1
        format: double
      Name:
        type: string
        description: Name is the unique Name of the Fruit.
        example: Apple
    description: A FruitManagement type describes a Fruit of e-store. (default view)
    example:
      Cost: 1
      Name: Apple
    required:
    - Name
    - Cost
  UserAddRequestBody:
    title: UserAddRequestBody
    type: object
    properties:
      UserName:
        type: string
        description: User Name
        example: Ea molestiae.
    example:
      UserName: Suscipit quidem vitae sit culpa.
    required:
    - UserName
  UserGetResponseBody:
    title: 'Mediatype identifier: application/vnd.user; view=default'
    type: object
    properties:
      ID:
        type: string
        description: ID is the unique id of the User.
        example: "1"
      UserName:
        type: string
        description: Name of the User
        example: Rakesh Mothukuri
    description: GetResponseBody result type (default view)
    example:
      ID: "1"
      UserName: Rakesh Mothukuri
    required:
    - ID
    - UserName
  UserManagementResponse:
    title: 'Mediatype identifier: application/vnd.user; view=default'
    type: object
    properties:
      ID:
        type: string
        description: ID is the unique id of the User.
        example: "1"
      UserName:
        type: string
        description: Name of the User
        example: Rakesh Mothukuri
    description: A UserManagement type describes a User of e-store. (default view)
    example:
      ID: "1"
      UserName: Rakesh Mothukuri
    required:
    - ID
    - UserName
  UserUserManagementResponseCollection:
    title: 'Mediatype identifier: application/vnd.user; type=collection; view=default'
    type: array
    items:
      $ref: '#/definitions/UserManagementResponse'
    description: ShowResponseBody is the result type for an array of UserManagementResponse (default view)
    example:
    - ID: "1"
      UserName: Rakesh Mothukuri
    - ID: "1"
      UserName: Rakesh Mothukuri
